name: Auto Tag - Semantic Patch Versioning

on:
  push:
    branches: develop

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch latest tag
        id: get_tag
        run: |
          git fetch --tags
          tag=$(git tag --sort=-creatordate | head -n1 || echo "0.0.0")
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump
        run: |
          version=${{ steps.get_tag.outputs.tag }}
          version=${version#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch+1))
          new_tag="v$major.$minor.$patch"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Push new tag
        run: |
          git config user.name "shivam962122"
          git config user.email "shivam962122@gmail.com"
          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}
