name: Auto Tag - Date Based Increment

on:
  push:
    branches:
      - develop

jobs:
  datever:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate date-based tag with increment
        id: create_tag
        run: |
          DATE=$(date +"%Y.%m.%d")
          i=1
          while true; do
            TAG="v${DATE}.${i}"
            if git ls-remote --tags origin | grep -q "refs/tags/${TAG}"; then
              echo "Tag ${TAG} already exists. Trying next..."
              i=$((i+1))
            else
              echo "Using tag: ${TAG}"
              echo "tag=${TAG}" >> $GITHUB_OUTPUT
              break
            fi
          done

      - name: Configure Git Identity
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create and Push Tag
        env:
          PAT: ${{ secrets.GH_PAT }}
        run: |
          TAG=${{ steps.create_tag.outputs.tag }}
          git tag "$TAG"
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }} "$TAG"
